### ISSUE TITLE
Subtask - Einstellungen Frontend

### ISSUE THREAD

**Issue by erikrei** [erikrei/ZahlenSchlau_react#40]
Der Benutzer soll in der Lage sein folgende Einstellungen anzupassen
- Spanne der Ergebnisse in der Zufallsabfrage (bei 10-30 liegen die Ergebnisse bei angegebenen Werten)
- Visuelles Lernen (on/off)

Falls das visuelle Lernen angeschaltet ist, aber die Spanne der Ergebnisse über 20 liegt, sollte eine Warnung angezeigt werden, damit der Benutzer weiß, dass das visuelle Lernen nur bedingt (bei Ergebnissen <= 20) angewendet wird.

- [x] Die Einstellungen können im Dashboard angepasst und gespeichert werden.
- [x] Die gespeicherten Einstellungen werden auf Klick eines "Speichern" Buttons ans Backend gesendet. 
- [x] Die Antwortmöglichkeiten werden automatisch in visueller Form angezeigt, wenn das visuelle Lernen angeschaltet ist.

**Comment by erikrei** [comment]
Subtask für #39 AK1
