### ISSUE TITLE
Subtask - Modifizierung Aufgabenlisten Backend

### ISSUE THREAD

**Issue by erikrei** [erikrei/ZahlenSchlau_react#57]
Je nach Anfrage werden die Aufgabenlisten folgend bearbeitet:
- [x] `DELETE /list`: Löscht die im body gegebene Aufgabenliste
- [x] `PUT /list/listname`: Verändert den Namen der Aufgabenliste mit dem im body gegebenen Namen
- [x] `PUT /list/exercises`: Verändert die Aufgaben der Aufgabenliste mit dem im body gegebenen Aufgaben

**Comment by erikrei** [comment]
Subtask für #56 AK1
