### ISSUE TITLE
Subtask - Lerneinheit Komponente

### ISSUE THREAD

**Issue by erikrei** [erikrei/ZahlenSchlau_react#7]
- [x] Die Applikation benötigt eine Komponente, in der verschiedene Arten von Lerneinheiten möglich sind
- [x] Die Komponente benötigt einen Header, durch den der Benutzer weiß wo er sich befindet und was genau er gerade lernt
- [x] Die Komponente enthält eine kurze Beschreibung der Aufgabenoperation, die gerade gelernt wird
- [x] Die Komponente enthält eine Komponente, in der Metadaten enthalten sind wie Anzahl der Aufgaben, welche Aufgabe gerade gelöst wird, wie die Aufgabe lautet, etc.
- [x] Die Komponente enthält die verschiedenen Antwortmöglichkeiten, die der Benutzer anklicken kann. Durch visuelles Feedback weiß der Benutzer, ob die Antwort richtig/falsch war
- [x] Zusätzlich enthält die Komponente eine Liste, in der alle bereits beantworteten Fragen stehen und wie diese gelöst wurden

**Comment by erikrei** [comment]
Subtask für #6 AK1
